from . import course
from . import academy_partner
from . import enrollment
from . import category
from . import product_template
from . import sale_order
from . import account_move
from . import sessions
from . import course_history